- hosts: all
  tasks:
   - name: stop container
     shell: docker stop webappcontainer111 
   - name: remove container
     shell: docker rm webappcontainer111
   - name: remove docker image
     shell: docker rmi sudeepgowda55/webapp
   - name: start container
     shell: docker container run -d --name webappcontainer111 -p 8080:8080 sudeepgowda55/webapp