- hosts: all
  tasks:
   - name: start container
     shell: docker container run -it --name webappcontainer -p 8080:8080 sudeepgowda55/webapp
  #  - name: remove container
  #    shell: docker container rm devopsProjectaa
  #  - name: remove docker image
  #    shell: docker image rmi devopsprojectaa
  #  - name: create new container
  #    shell: docker container run -itd --name devopsProjectaa -p 7000:8080 vikashashoke/docker_image